### ISSUE TITLE
roo-xls needed ?

### ISSUE THREAD

**Issue by jsfenfen** [openelections/fec_results#14]
I'm an idiot with ruby, but I'm getting the below error. What I really want is 2014 results, but... 

irb(main):004:0> c = FecResults::Congress.new(:year => 2012)
=> #<FecResults::Congress:0x007f9972239610 @year=2012, @url="http://www.fec.gov/pubrec/fe2012/2012congresults.xls">
irb(main):005:0> results = c.results
RuntimeError: Excel support has been extracted to roo-xls due to its dependency on the GPL'd spreadsheet gem. Install roo-xls to use Roo::Excel.
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/roo-2.4.0/lib/roo.rb:22:in `const_missing'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/remote_table-3.3.3/lib/remote_table/xls.rb:8:in `roo_class'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/remote_table-3.3.3/lib/remote_table/processed_by_roo.rb:11:in `_each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/remote_table-3.3.3/lib/remote_table.rb:478:in `each'
	from /Users/jfenton/github-whitelabel/openelections_fec/fec_results/lib/fec_results/congress.rb:22:in `entries'
	from /Users/jfenton/github-whitelabel/openelections_fec/fec_results/lib/fec_results/congress.rb:22:in `process_2012'
	from /Users/jfenton/github-whitelabel/openelections_fec/fec_results/lib/fec_results/congress.rb:16:in `results'
	from (irb):5
	from /usr/local/var/rbenv/versions/2.3.0/bin/irb:11:in `<main>'

**Comment by dwillis** [comment]
I'm an idiot, too, apparently. Will have a fix.

**Comment by jsfenfen** [comment]
Huh, maybe this is upstream? It seems like changing:
require 'roo' 
to:
require 'roo-xls' 
here: https://github.com/seamusabshere/remote_table/blob/master/lib/remote_table/processed_by_roo.rb#L9
and installing roo-xls makes the error change...

**Comment by jsfenfen** [comment]
One random other thing is that it looks like FEC has corrected a misspelled sheet name from 2012 since this was written--adding the missing 'l' seems to work, i.e.: 

diff --git a/lib/fec_results/congress.rb b/lib/fec_results/congress.rb
index ae7a427..fb4d1b6 100644
--- a/lib/fec_results/congress.rb
+++ b/lib/fec_results/congress.rb
@@ -18,7 +18,7 @@ module FecResults
 
     def process_2012(options)
       results = []
-      t = RemoteTable.new(url, :sheet => "2012 US House & Senate Resuts")
+      t = RemoteTable.new(url, :sheet => "2012 US House & Senate Results")
       rows = t.entries
       rows = rows.select{|r| r['D'] == options[:chamber]} if options[:chamber]
       rows = rows.select{|r| r['STATE ABBREVIATION'] == options[:state]} if opt
