### ISSUE TITLE
2014 data

### ISSUE THREAD

**Issue by jsfenfen** [openelections/fec_results#16]
I think I've got congress for 2014 working here https://github.com/jsfenfen/fec_results/commit/9ade8d146c301f8298947e976e8b7abc2ed8e12f  but need to verify if anything is missing.

**Comment by dwillis** [comment]
Hey, I just released an updated version of the gem (0.7) that includes 2014 and fixes the roo issue.

**Comment by jsfenfen** [comment]
Awesome. Thanks!
